### ISSUE TITLE
Nb résultats différent du nombre de liens

### ISSUE THREAD

**Issue by amrani34** [GaryPEGEOT/MiaouProject#14]
En recherches exact, comment est il possible que le nombre de résultat est différent du nombre de liens ? 

Pour "crédit travaux" en exact, si il y a 42 liens, ça signifie qu'il y a 42 sites avec des phrases comportant" crédit travaux", et pourtant il n'y a que 22 résultats … 

![Uploading Capture d’écran 2015-01-19 à 23.44.52.png . . .]()

**Comment by GaryPEGEOT** [comment]
Filtre de recherche trop strict (phrase trop courte, caractère interdit,
...)

Gary PEGEOT
Résidence le Mazet
363 Route de Sisteron
13100 Aix-en-Provence
@: garypegeot@gmail.com
☎: 06.32.50.65.92
